[package]
name = "bl-bot"
version = "0.8.0"
description = "Beat Leader Discord Bot"
readme = "README.md"
repository = "https://github.com/motzel/bl-bot"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "^0.10"
log = "^0.4"
reqwest = { version = "^0.11", features = ["json", "rustls-tls", "gzip", "brotli"] }
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
tokio = { version = "^1.32.0", features = ["full"] }
poise = { version = "^0.5", features = ["cache"] }
shuttle-persist = "^0.29"
shuttle-poise = "^0.29"
shuttle-runtime = "^0.29"
shuttle-secrets = "^0.29"
tracing = "^0.1.38"
futures = "^0.3.0"
lazy_static = "^1.4.0"
peak_alloc = "^0.2.0"
governor = "^0.6.0"
serde_with = {version = "^3.2.0", features = ["chrono"]}
regex = "^1.9.3"
chrono = {version = "^0.4.0", features = ["serde"] }
serde_repr = "^0.1.0"
ril = { version = "^0.9.0", features = ["all-pure"] }
stackblur-iter = "^0.2.0"
bytes = "^1.5.0"
relativetime = {version = "^0.1.0", features = ["chrono"] }
async-trait = "^0.1.0"
