[package]
name = "bl-bot"
version = "0.5.0"
description = "Beat Leader Discord Bot"
readme = "README.md"
repository = "https://github.com/motzel/bl-bot"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "^0.10"
log = "^0.4"
reqwest = { version = "^0.11", features = ["json", "rustls-tls", "gzip", "brotli"] }
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
tokio = { version = "^1.29.1", features = ["full"] }
poise = { version = "^0.5", features = ["cache"] }
shuttle-persist = "^0.24"
shuttle-poise = "^0.24"
shuttle-runtime = "^0.24"
shuttle-secrets = "^0.24"
tracing = "^0.1.37"
futures = "^0.3.28"
lazy_static = "^1.4.0"
peak_alloc = "^0.2.0"
governor = "^0.6.0"
serde_with = {version = "^3.2.0", features = ["chrono"]}
regex = "^1.9.3"
chrono = {version = "^0.4.26", features = ["serde"] }
serde_repr = "^0.1.16"
