DISCORD_TOKEN = 'the contents of my discord token'
REFRESH_INTERVAL = "600" # seconds

# uncomment to enable oauth features (clan invites for now)
#OAUTH_CLIENT_ID = "your bl oauth app id"
#OAUTH_CLIENT_SECRET = "your bl oauth app secret"
#OAUTH_REDIRECT_URI = "your bl oauth app redirect uri"