name: "Test"

on:
  pull_request:
  push:
    branches:
      - master
    tags-ignore:
      - '**'
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: "cargo check"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: '${{ runner.os }}-cargo-registry-${{ hashFiles(''**/Cargo.lock'') }}'

      - uses: dtolnay/rust-toolchain@stable

      - run: cargo check

  test:
    name: "cargo test"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: '${{ runner.os }}-cargo-registry-${{ hashFiles(''**/Cargo.lock'') }}'

      - uses: dtolnay/rust-toolchain@stable

      - run: cargo test

  fmt:
    name: "cargo fmt"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: '${{ runner.os }}-cargo-registry-${{ hashFiles(''**/Cargo.lock'') }}'

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - run: cargo fmt --all -- --check

  clippy:
    name: "cargo clippy"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: '${{ runner.os }}-cargo-registry-${{ hashFiles(''**/Cargo.lock'') }}'

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - run: cargo clippy -- -D warnings